SELECT * FROM Podcast
FETCH FIRST 5 ROWS ONLY;


SELECT * FROM Subscription
FETCH FIRST 5 ROWS ONLY;

SELECT * FROM Audiofile
FETCH FIRST 5 ROWS ONLY;

SELECT * FROM b_user
FETCH FIRST 5 ROWS ONLY;

SELECT * FROM Podcast
FETCH FIRST 5 ROWS ONLY;

SELECT * FROM Administrator
FETCH FIRST 5 ROWS ONLY;

SELECT * FROM Artist
FETCH FIRST 5 ROWS ONLY;

SELECT * FROM Playlist
FETCH FIRST 5 ROWS ONLY;

SELECT * FROM Podcast_Episode
FETCH FIRST 5 ROWS ONLY;

SELECT * FROM Stream
FETCH FIRST 5 ROWS ONLY;

SELECT * FROM Album
FETCH FIRST 5 ROWS ONLY;

SELECT * FROM Podcast
FETCH FIRST 5 ROWS ONLY;

SELECT * FROM Song
FETCH FIRST 5 ROWS ONLY;

SELECT * FROM Follows_Playlist
FETCH FIRST 5 ROWS ONLY;

SELECT * FROM Follows_Podcast
FETCH FIRST 5 ROWS ONLY;

SELECT * FROM Follows_Artist
FETCH FIRST 5 ROWS ONLY;

SELECT * FROM Playlist_Has_Song
FETCH FIRST 5 ROWS ONLY;